### ISSUE TITLE
No connection could be made 

### ISSUE THREAD

**Issue by VahidAalamiAleagha** [miladrahimi/v2ray-docker-compose#8]
Hi, I got this error would you please help me, Does it happen because of my configuration or government censorship?
|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by miladrahimi** [comment]
Please check the configs (IP, Port, Passwords, etc) carefully. If they are correct so you might need to migrate ro another hosting. for example arvan cloud servers block your proxies, try afranet.
